name: Update translations

on:
  # Check for updates every sunday
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ V3 ]
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Update translations
      uses: crowdin/github-action@v1.13.1
      with:
        download_translations: true
        commit_message: '[automated] update translations from Crowdin'
        push_translations: true
        localization_branch_name: V3_i18n
        crowdin_branch_name: V3
        create_pull_request: true
        pull_request_title: 'Update translations from Crowdin'
        pull_request_body: 'Merge this to add changes from Crowdin to this repo.'
        pull_request_labels: 'crowdin'
        config: crowdin.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
